In [115]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [116]:
gait = pd.read_csv("gaitFull.csv")

In [117]:
gait

P1  P2  P3  P4    x1     y1     z1    x2     y2    z2    r  label
0      0   0   1   1 -0.29  -9.70   3.97  0.08  -9.31  0.27  161      0
1      0   0   1   1  0.05  -9.51   4.45  0.27  -9.05 -0.67  151      0
2      0   0   1   1  0.78  -9.48   6.54  1.96  -8.99  2.08  146      1
3      0   0   1   1  5.77  -6.85   3.06 -0.24  -8.95  6.86  144      1
4      0   0   1   1  0.45  -9.52  -0.36  0.39  -9.85  2.25  143      1
...   ..  ..  ..  ..   ...    ...    ...   ...    ...   ...  ...    ...
2371   1   1   0   0 -5.31 -10.97  -6.63 -1.89 -10.10 -3.29  288      5
2372   1   1   0   0 -0.86  -9.70  -1.71 -3.69  -9.92 -2.17  276      5
2373   1   1   0   0 -0.79 -10.07  -3.23 -1.73  -9.16  1.32  251      5
2374   1   1   0   0  0.31 -10.10   3.14  3.06  -8.72 -0.20  209      6
2375   1   1   0   0 -5.58 -12.75 -12.72 -5.73  -9.52  0.83  166      6

[2376 rows x 12 columns]

In [118]:
X = gait.drop('label',  axis=1)
y = gait['label']

In [119]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [120]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
  
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test) 

In [121]:
X_train

array([[ 0.93574408,  1.0375465 , -1.02235508, ...,  2.06521425,
        -0.2343915 ,  1.88076492],
       [ 0.93574408,  1.0375465 , -1.02235508, ..., -0.76812637,
        -0.74726145, -0.46735649],
       [ 0.93574408,  1.0375465 , -1.02235508, ..., -1.33899722,
        -0.58516266, -0.58476256],
       ...,
       [ 0.93574408,  1.0375465 , -1.02235508, ...,  0.63278371,
        -0.02711763,  1.58724974],
       [-1.06866826, -0.96381223, -1.02235508, ...,  0.07592195,
         0.25721959, -0.97220259],
       [ 0.93574408,  1.0375465 , -1.02235508, ...,  0.14946973,
        -0.47355365,  1.97468978]])

In [110]:
from sklearn.decomposition import PCA 
  
pca = PCA(n_components = 8) 
  
X_train = pca.fit_transform(X_train) 
X_test = pca.transform(X_test) 
  
explained_variance = pca.explained_variance_ratio_ 

In [111]:
from sklearn.model_selection import GridSearchCV 
  
# defining parameter range 
param_grid = {'C': [1000],  
              'gamma': [ 0.0001], 
              'kernel': ['rbf']}  
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3) 
  
# fitting the model for grid search 
grid.fit(X_train, y_train) 

/Users/adithya/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.


Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.514, total=   0.2s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.2s remaining:    0.0s


[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.487, total=   0.2s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.5s remaining:    0.0s


[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.514, total=   0.3s


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.8s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [1000], 'gamma': [0.0001], 'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [112]:
print(grid.best_params_) 
  
# print how our model looks after hyper-parameter tuning 
print(grid.best_estimator_) 

{'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}
SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [113]:
grid_predictions=grid.predict(X_test)

In [114]:
print(classification_report(y_test, grid_predictions)) 

              precision    recall  f1-score   support

           0       0.37      0.61      0.46        57
           1       0.43      0.47      0.45        55
           2       0.55      0.41      0.47        71
           3       0.45      0.32      0.37        53
           4       0.53      0.54      0.54        59
           5       0.39      0.40      0.40        57
           6       0.48      0.58      0.53        74
           7       0.39      0.18      0.25        50

    accuracy                           0.45       476
   macro avg       0.45      0.44      0.43       476
weighted avg       0.46      0.45      0.44       476



In [94]:
print(classification_report(y_test, grid_predictions))

              precision    recall  f1-score   support

           0       0.53      0.64      0.58        69
           1       0.35      0.51      0.41        51
           2       0.58      0.43      0.50        58
           3       0.59      0.23      0.33        56
           4       0.53      0.66      0.59        67
           5       0.40      0.36      0.38        56
           6       0.38      0.76      0.51        59
           7       1.00      0.03      0.06        60

    accuracy                           0.46       476
   macro avg       0.55      0.45      0.42       476
weighted avg       0.55      0.46      0.43       476



In [70]:
print(confusion_matrix(y_test, grid_predictions))

[[39 16  0  0  4  7  5  0]
 [15 19  2  0  0  5  2  0]
 [ 9 15 27  3  1  1 11  2]
 [ 4  2  6  1 26  3  3  1]
 [ 3  7  5  0 45  5  1  0]
 [ 3  2  3  1 25 22  7  0]
 [ 2  2  2  0  6  9 38  2]
 [26  1  3  0  6  5 16  0]]


In [45]:
gait = pd.read_csv("gaitFullModified2.csv")

In [46]:
X = gait.drop('label',  axis=1)
y = gait['label']

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [48]:
from sklearn.preprocessing import StandardScaler 
sc = StandardScaler() 
  
X_train = sc.fit_transform(X_train) 
X_test = sc.transform(X_test) 

In [49]:
from sklearn.model_selection import GridSearchCV 
  
# defining parameter range 
param_grid = {'C': [1000],  
              'gamma': [0.0001], 
              'kernel': ['rbf']}  
  
grid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3) 
  
# fitting the model for grid search 
grid.fit(X_train, y_train) 

/Users/adithya/opt/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.2s remaining:    0.0s


Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.570, total=   0.1s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.656, total=   0.1s
[CV] C=1000, gamma=0.0001, kernel=rbf ................................
[CV] .... C=1000, gamma=0.0001, kernel=rbf, score=0.617, total=   0.1s


[Parallel(n_jobs=1)]: Done   3 out of   3 | elapsed:    0.2s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [1000], 'gamma': [0.0001], 'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [50]:
print(grid.best_params_) 
  
# print how our model looks after hyper-parameter tuning 
print(grid.best_estimator_) 

{'C': 1000, 'gamma': 0.0001, 'kernel': 'rbf'}
SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.0001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)


In [28]:
grid_predictions=grid.predict(X_test)

In [29]:
print(classification_report(y_test, grid_predictions)) 

              precision    recall  f1-score   support

           1       0.63      0.44      0.52        77
           2       0.64      0.62      0.63       174
           3       0.49      0.58      0.53        62
           4       0.62      0.68      0.65       163

    accuracy                           0.61       476
   macro avg       0.59      0.58      0.58       476
weighted avg       0.61      0.61      0.61       476



In [30]:
print(confusion_matrix(y_test, grid_predictions))

[[ 34  26   2  15]
 [  5 108  19  42]
 [  1  13  36  12]
 [ 14  21  17 111]]


In [31]:
grid

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [1000], 'gamma': [0.0001], 'kernel': ['rbf']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)